In [12]:
import numpy as np
import pandas as pd
from scipy import stats

In [4]:
#Exercise 1

#a = 8, 12, 16, 24, 4

#sum(a)
#64/5


first_array = np.array([8, 12, 16, 24, 4])
print(np.std(first_array))

6.881860213634101


In [5]:
 a = 9+12+17+20+13+10+6+5+3
 a /2



47.5

In [6]:
#exercise 4 conc, order, get middle value

a = np.array([[10, 10, 10, 10, 11, 11, 12, 13, 14],
[15, 15, 15, 16, 16, 16, 16, 16, 17, 18, 19, 19],
[20, 20, 20, 21, 21, 21, 21, 21, 22, 22, 22, 23, 23, 23, 24, 24, 24],
[26, 26, 26, 26, 26, 26, 26, 27, 27, 27, 27, 29, 29, 29, 29, 29, 29, 29, 29, 29],
[30, 30, 30, 30, 30, 31, 31, 32, 32, 33, 33, 34, 34],
[35, 35, 35, 37, 37, 37, 37, 39, 39, 39],
[40, 40, 43, 43, 44, 44],
[46, 46, 46, 47, 49],
[52, 53, 54]])



/var/folders/6n/sf43sj591qd37_1r77rmw6v00000gn/T/ipykernel_1547/1547056068.py:3: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  a = np.array([[10, 10, 10, 10, 11, 11, 12, 13, 14],


In [7]:
onedim_arr = np.array ([1,2,3])

print (onedim_arr)

[1 2 3]


In [13]:
a = (46, 46, 46, 47, 49)
arr.sum()


NameError: name 'arr' is not defined

In [9]:
# mean of (46, 46, 46, 47, 49) Change occurrs when one nr is removed!

values = 46, 46, 46, 47, 49

print(np.mean(values))

46.8


In [10]:
# median of (46, 46, 46, 47, 49) There is no change when removing a nr!

values = 46, 46, 46, 47, 49

print(np.median(values))

46.0


In [14]:
# mode of (46, 46, 47, 49) There is a change depending on what nr is removed! I think. 

values = 46, 47, 49

print(stats.mode(values))

ModeResult(mode=array([46]), count=array([1]))


In [15]:
#random, just to check
arr = np.random.randn(4,4)
arr.sum()

-3.753731625543799

In [16]:
#exercise 9 we need the mean first?
#sal är 150, delat med emp (10) är 15 eur per timme.

sal = ([[25, 40, 35, 50,], [3, 2, 1, 4]])




In [17]:
#exercise 9

my_array = np.array([[25, 40, 35, 50],
                    [3, 2, 1, 4]])
print(my_array)

np.std(my_array)

[[25 40 35 50]
 [ 3  2  1  4]]


18.641351882307248

In [19]:
#Exercise 11 I need to do this.


#A) mu=5, sigma =1.5
#B) mu=10, sigma =1.0
#C) mu=5, sigma =1.65
#D) mu=8, sigma =1.2
#E) mu=10, sigma =1.6
